### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by Menedenz** [Menedenz/github-crash-course#1]
I think it looks better if you the main title is a bit more orange.

The styling rule cloud be changed like this:
```css
h1{
  color: #efa82e
}
```
